"""Tests for .github/scripts/assemble-changelog.mjs (the CLI surface).

These drive the assembler's CLI (`--check` / `--draft` / `--release`) the way the
release bash scripts do, so a regression in the contract those scripts depend on
fails CI. The CLI exercises the exported helpers end to end (fragment parsing,
category ordering, the changelog roll); there is no separate in-repo unit test of
the helper functions.
"""

import shutil
import subprocess
from pathlib import Path

import pytest

pytestmark = pytest.mark.skipif(
    shutil.which("node") is None, reason="node not available"
)

REPO_ROOT = Path(
    subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
)
SCRIPT = REPO_ROOT / ".github" / "scripts" / "assemble-changelog.mjs"
RELEASE_MARKER = (
    "<!-- New releases are inserted below by "
    ".github/scripts/assemble-changelog.mjs; do not edit this file by hand. -->"
)


def run(cwd: Path, *args: str) -> subprocess.CompletedProcess:
    """Invoke the assembler CLI with `cwd` as the working directory."""
    return subprocess.run(
        ["node", str(SCRIPT), *args],
        cwd=cwd,
        capture_output=True,
        text=True,
    )


def write_fragment(cwd: Path, name: str, content: str) -> None:
    frag_dir = cwd / "changelog.d"
    frag_dir.mkdir(exist_ok=True)
    (frag_dir / name).write_text(content)


def write_changelog(cwd: Path) -> Path:
    path = cwd / "CHANGELOG.md"
    path.write_text(
        "# Changelog\n\n## Unreleased\n\n"
        f"{RELEASE_MARKER}\n\n## [0.4.0] - 2026-06-13\n\n### Added\n\n- prior\n"
    )
    return path


def test_marker_in_repo_changelog_matches_script() -> None:
    """The committed CHANGELOG.md must carry the exact marker the script edits."""
    assert RELEASE_MARKER in (REPO_ROOT / "CHANGELOG.md").read_text()


def test_check_counts_fragments(tmp_path: Path) -> None:
    write_fragment(tmp_path, "1.added.md", "- a")
    write_fragment(tmp_path, "2.fixed.md", "- b")
    result = run(tmp_path, "--check")
    assert result.returncode == 0
    assert result.stdout.strip() == "changelog.d: 2 fragments valid."


def test_check_singular(tmp_path: Path) -> None:
    write_fragment(tmp_path, "1.added.md", "- a")
    assert run(tmp_path, "--check").stdout.strip() == "changelog.d: 1 fragment valid."


def test_draft_orders_by_category(tmp_path: Path) -> None:
    write_fragment(tmp_path, "2.fixed.md", "- a fix")
    write_fragment(tmp_path, "1.added.md", "- a feature")
    result = run(tmp_path, "--draft")
    assert result.returncode == 0
    assert result.stdout.strip() == "### Added\n\n- a feature\n\n### Fixed\n\n- a fix"


def test_draft_empty_when_no_fragments(tmp_path: Path) -> None:
    result = run(tmp_path, "--draft")
    assert result.returncode == 0
    assert result.stdout.strip() == ""


def test_dotted_fragment_id_is_accepted(tmp_path: Path) -> None:
    # The id segment is greedy: only the trailing `.<category>.md` is the
    # category, so a multi-segment id like `1.2` stays valid.
    write_fragment(tmp_path, "1.2.added.md", "- dotted id")
    result = run(tmp_path, "--draft")
    assert result.returncode == 0
    assert result.stdout.strip() == "### Added\n\n- dotted id"


def test_invalid_fragment_name_fails_loudly(tmp_path: Path) -> None:
    write_fragment(tmp_path, "oops.md", "- x")
    result = run(tmp_path, "--check")
    assert result.returncode == 1
    assert "not a valid fragment name" in result.stderr
    assert "added, changed, deprecated, removed, fixed, security" in result.stderr


def test_empty_fragment_fails_loudly(tmp_path: Path) -> None:
    write_fragment(tmp_path, "1.added.md", "   \n  ")
    result = run(tmp_path, "--check")
    assert result.returncode == 1
    assert "fragment is empty" in result.stderr


def test_release_rolls_changelog_and_deletes_fragments(tmp_path: Path) -> None:
    path = write_changelog(tmp_path)
    write_fragment(tmp_path, "1.added.md", "- new thing")
    write_fragment(tmp_path, "2.fixed.md", "- a fix")

    result = run(tmp_path, "--release", "0.5.0", "--date", "2026-06-14")
    assert result.returncode == 0
    assert result.stdout.strip() == (
        "Released ## [0.5.0] - 2026-06-14; removed 2 fragment(s)."
    )

    out = path.read_text()
    # Newest section sits between the marker and the previous release.
    assert out.index(RELEASE_MARKER) < out.index("## [0.5.0]") < out.index("## [0.4.0]")
    assert (
        "## [0.5.0] - 2026-06-14\n\n### Added\n\n- new thing\n\n### Fixed\n\n- a fix"
        in out
    )
    assert "## Unreleased\n" in out
    assert not (tmp_path / "changelog.d" / "1.added.md").exists()
    assert not (tmp_path / "changelog.d" / "2.fixed.md").exists()


def test_release_without_fragments_fails(tmp_path: Path) -> None:
    write_changelog(tmp_path)
    (tmp_path / "changelog.d").mkdir(exist_ok=True)
    result = run(tmp_path, "--release", "0.5.0", "--date", "2026-06-14")
    assert result.returncode == 1
    assert "No changelog fragments to release" in result.stderr


def test_release_without_marker_fails(tmp_path: Path) -> None:
    (tmp_path / "CHANGELOG.md").write_text("# Changelog\n\n## Unreleased\n")
    write_fragment(tmp_path, "1.added.md", "- new thing")
    result = run(tmp_path, "--release", "0.5.0", "--date", "2026-06-14")
    assert result.returncode == 1
    assert "missing the release marker" in result.stderr


def test_release_rejects_stray_positional(tmp_path: Path) -> None:
    write_changelog(tmp_path)
    write_fragment(tmp_path, "1.added.md", "- a feature")
    # A bare date without the --date flag must fail loudly, not silently stamp
    # today's date into the immutable CHANGELOG.md.
    result = run(tmp_path, "--release", "0.5.0", "2026-06-14")
    assert result.returncode == 1
    assert "unexpected argument(s) after --release" in result.stderr


def test_release_date_flag_without_value_fails(tmp_path: Path) -> None:
    write_changelog(tmp_path)
    write_fragment(tmp_path, "1.added.md", "- a feature")
    result = run(tmp_path, "--release", "0.5.0", "--date")
    assert result.returncode == 1
    assert "--date requires a YYYY-MM-DD argument" in result.stderr


def test_unknown_mode_prints_general_usage(tmp_path: Path) -> None:
    result = run(tmp_path, "--wat")
    assert result.returncode == 1
    assert "usage: assemble-changelog.mjs [--check" in result.stderr
