name: "Setup Base Environment"
description: "Sets up Node.js with pnpm and caching. Optionally sets up Python with uv."
inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: "22"
  setup-python:
    description: "Whether to set up Python with uv"
    required: false
    default: "false"
  python-version:
    description: "Python version to use (if setup-python is true)"
    required: false
    default: "3.11"

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Restore pnpm cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install Node Dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Set up uv
      if: inputs.setup-python == 'true'
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      if: inputs.setup-python == 'true'
      run: uv python install ${{ inputs.python-version }}
      shell: bash

    - name: Install Python Dependencies
      if: inputs.setup-python == 'true'
      run: uv sync --frozen
      shell: bash
